#!/usr/bin/env bash
# shellcheck shell=bash

set -eo pipefail

/decode-headers.py \
    --header "Subject" \
    --header "From" \
    --header "X-SomethingElse" \
    --socketspec "inet:8899:127.0.0.1" \
    --timeout 300 \
    2>&1 | awk -W Interactive '{print "[decode-headers] " $0}'
